# Generated by Django 4.0 on 2021-12-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_telefono', models.DecimalField(decimal_places=0, max_digits=15)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fecha_de_registro', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=100)),
                ('imagen_usuario', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
