# Generated by Django 4.0 on 2021-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_telefono',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
    ]
