# Generated by Django 4.0 on 2021-12-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Lector'), (2, 'Escritor')], default=1),
        ),
    ]
