# Generated by Django 4.0 on 2021-12-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen_usuario',
        ),
    ]
