# Generated by Django 4.0 on 2021-12-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentario',
            table='comentarios',
        ),
    ]
