# Generated by Django 3.2.9 on 2021-12-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen_usuario',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen_publicacion',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
