# Generated by Django 4.0 on 2021-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='publicacion',
            name='guardar_como_borrador',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='resumen',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='categorias',
            field=models.ManyToManyField(to='publicaciones.Categoria'),
        ),
    ]
