# Generated by Django 4.0 on 2021-12-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
    ]
